version: '3.8'

services:
  city_sampler:
    build: .
    container_name: city_sampler
    volumes:
    -  ./Datasets:/app/Datasets
    env_file:
    -  .env 
  
  data_ingestion:
    build: .
    container_name: data_ingestion
    volumes:
    -  ./Datasets:/app/Datasets
    depends_on:
      - city_sampler
    env_file:
      - .env

  generate_sql_inserts:
    build: .
    container_name: generate_sql_inserts
    volumes: 
      - ./Datasets:/app/Datasets
      - ~/docker/postgres-init:/docker-entrypoint-initdb.d
    depends_on:
      - data_ingestion

  db:
    image: postgres:13
    container_name: bike_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bike_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ~/docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  pgdata:
  
